# Generated by Django 5.2.5 on 2025-10-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Barát', 'verbose_name_plural': 'Barátok'},
        ),
        migrations.AddField(
            model_name='friend',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(help_text='Add here the name of your friend', max_length=100, verbose_name='Friend Name'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_phone_name_combination'),
        ),
        migrations.AlterModelTable(
            name='friend',
            table='main_friend',
        ),
    ]
