# Generated by Django 5.2.5 on 2025-10-09 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_friend_options_friend_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='version_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
