# Generated by Django 5.2.5 on 2025-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A videó címe', max_length=200, verbose_name='Cím')),
                ('url', models.URLField(help_text='A videó URL címe', verbose_name='Video link')),
                ('description', models.TextField(blank=True, help_text='A videó leírása', verbose_name='Leírás')),
                ('category', models.CharField(choices=[('education', 'Oktatás'), ('music', 'Zene'), ('entertainment', 'Szórakozás'), ('tech', 'Technológia'), ('other', 'Egyéb')], default='other', help_text='A videó kategóriája', max_length=50, verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'videó lista',
                'verbose_name_plural': 'Videók',
                'ordering': ['title'],
            },
        ),
    ]
