# Generated by Django 5.2.5 on 2025-10-13 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('version_number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
